#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_TOUCHSCREEN_GT9XX)		+= gt9xx.o gt9xx_update.o goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX)		+= himax_ts.o
obj-$(CONFIG_TOUCHSCREEN_IT7260)	+= it7260_mts.o
obj-$(CONFIG_TOUCHSCREEN_1WIRE)		+= 1wire_host.o
obj-$(CONFIG_TOUCHSCREEN_IF)		+= ts-if.o
