obj-y		+= fci.o

fci-objs := src/bbm.o
fci-objs += src/fc8300.o
fci-objs += src/fc8300_bb.o
fci-objs += src/fc8300_i2c.o
fci-objs += src/fc8300_isr.o
fci-objs += src/fc8300_ppi.o
fci-objs += src/fc8300_spi.o
fci-objs += src/fc8300_tun_table.o
fci-objs += src/fc8300b_tun_table.o
fci-objs += src/fci_hal.o
fci-objs += src/fci_hpi.o
fci-objs += src/fci_oal.o
fci-objs += src/fci_ringbuffer.o
fci-objs += src/fci_tun.o
fci-objs += src/fc8300_tun.o
fci-objs += src/fc8300b_tun.o

EXTRA_CFLAGS += -Idrivers/misc/fci/inc
