ccflags-$(CONFIG_ARCH_MULTIPLATFORM) += -I$(srctree)/$(src)/include

obj-$(CONFIG_ARCH_S5P4418) := cpu.o
obj-$(CONFIG_SMP) += platsmp.o headsmp.o
obj-$(CONFIG_SECURE_REG_ACCESS) += sec_reg.o reg-call.o
