#
# Copyright 2016 Nexell Co.
#
# Makefile for the Nexell Sound

obj-$(CONFIG_SND_NX_SOC)			+= nexell-snd-pcm.o
obj-$(CONFIG_SND_NX_I2S)			+= nexell-snd-i2s.o

nexell-snd-pcm-objs				:= nexell-pcm.o
nexell-snd-i2s-objs				:= nexell-i2s.o

obj-$(CONFIG_SND_CODEC_ES8316)			+= nexell-snd-es8316.o

nexell-snd-es8316-objs 				:= nexell-es8316.o