/*
 * Copyright (IRQ_OFFSET +C) 2016  Nexell Co., Ltd.
 * Author: Youngbok, Park <ybpark@nexell.co.kr>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (IRQ_OFFSET +at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _NXP5540_IRQ_H
#define _NXP5540_IRQ_H

/*
 * GIC remmap hwirq to hwirq  SPI 32 ~
 */
#define IRQ_OFFSER				(0)
#define IRQ_MCUSTOP				(IRQ_OFFSET + 0)
#define IRQ_CLKPWR_INT_CEC			(IRQ_OFFSET + 1)
#define IRQ_CLKPWR_INTREQPWR			(IRQ_OFFSET + 2)
#define IRQ_CLKPWR_ALIVEIRQ			(IRQ_OFFSET + 3)
#define IRQ_CLKPWR_RTCIRQ			(IRQ_OFFSET + 4)
#define IRQ_UART0				(IRQ_OFFSET + 5)
#define IRQ_UART1				(IRQ_OFFSET + 6)
#define IRQ_UART2				(IRQ_OFFSET + 7)
#define IRQ_UART3				(IRQ_OFFSET + 8)
#define IRQ_UART4				(IRQ_OFFSET + 9)
#define IRQ_UART5				(IRQ_OFFSET + 10)
#define IRQ_SSP0				(IRQ_OFFSET + 11)
#define IRQ_SSP1				(IRQ_OFFSET + 12)
#define IRQ_SSP2				(IRQ_OFFSET + 13)
#define IRQ_I2C0				(IRQ_OFFSET + 14)
#define IRQ_I2C1				(IRQ_OFFSET + 15)
#define IRQ_I2C2				(IRQ_OFFSET + 16)
#define IRQ_DEINTERLACE				(IRQ_OFFSET + 17)
#define IRQ_WDT1				(IRQ_OFFSET + 18)
#define IRQ_WDT1				(IRQ_OFFSET + 18)
#define IRQ_AC97				(IRQ_OFFSET + 19)
#define IRQ_SPDIFRX				(IRQ_OFFSET + 20)
#define IRQ_SPDIFTX				(IRQ_OFFSET + 21)
#define IRQ_TIMER0_INT0				(IRQ_OFFSET + 22)
#define IRQ_TIMER0_INT1				(IRQ_OFFSET + 23)
#define IRQ_TIMER0_INT2				(IRQ_OFFSET + 24)
#define IRQ_TIMER0_INT3				(IRQ_OFFSET + 25)
#define IRQ_PWM0_INT0				(IRQ_OFFSET + 26)
#define IRQ_PWM0_INT1				(IRQ_OFFSET + 27)
#define IRQ_PWM0_INT2				(IRQ_OFFSET + 28)
#define IRQ_PWM0_INT3				(IRQ_OFFSET + 29)
#define IRQ_WDT0				(IRQ_OFFSET + 30)
#define IRQ_MPEGTSI_CORE			(IRQ_OFFSET + 31)
#define IRQ_DISP_DPC_PRI			(IRQ_OFFSET + 32)
#define IRQ_DISP_DPC_SEC			(IRQ_OFFSET + 33)
#define IRQ_NXS_TO_HDMI				(IRQ_OFFSET + 34)
#define IRQ_HDMI				(IRQ_OFFSET + 35)
#define IRQ_VIP1_SYNC				(IRQ_OFFSET + 36)
#define IRQ_VIP0_SYNC				(IRQ_OFFSET + 37)
#define IRQ_LVDS1				(IRQ_OFFSET + 38)
#define IRQ_PPM_INT1				(IRQ_OFFSET + 39)
#define IRQ_ADC					(IRQ_OFFSET + 40)
#define IRQ_PPM_INT0				(IRQ_OFFSET + 41)
#define IRQ_SDMMC0				(IRQ_OFFSET + 42)
#define IRQ_SDMMC1				(IRQ_OFFSET + 43)
#define IRQ_SDMMC2				(IRQ_OFFSET + 44)
#define IRQ_CODA_HOST				(IRQ_OFFSET + 45)
#define IRQ_CODA_JPG				(IRQ_OFFSET + 46)
#define IRQ_CODA_VPU				(IRQ_OFFSET + 47)
#define IRQ_USB20OTG				(IRQ_OFFSET + 48)
#define IRQ_USB20HOST				(IRQ_OFFSET + 49)
#define IRQ_USB20HOST_OHCI			(IRQ_OFFSET + 50)
#define IRQ_USB20HOST_EHCI			(IRQ_OFFSET + 51)
#define IRQ_PPM_INT2				(IRQ_OFFSET + 52)
#define IRQ_PPM_INT3				(IRQ_OFFSET + 53)
#define IRQ_PPM_INT4				(IRQ_OFFSET + 54)
#define IRQ_PPM_INT5				(IRQ_OFFSET + 55)
#define IRQ_PPM_INT6				(IRQ_OFFSET + 56)
#define IRQ_CRYPTO				(IRQ_OFFSET + 57)
#define IRQ_PDM0				(IRQ_OFFSET + 58)
#define IRQ_TMU_BBUS				(IRQ_OFFSET + 60)
#define IRQ_PPM_INT7				(IRQ_OFFSET + 62)
#define IRQ_PPM_INT8				(IRQ_OFFSET + 63)
#define IRQ_I2S0				(IRQ_OFFSET + 64)
#define IRQ_I2S1				(IRQ_OFFSET + 65)
#define IRQ_I2S2				(IRQ_OFFSET + 66)
#define IRQ_I2S3				(IRQ_OFFSET + 67)
#define IRQ_DWC_GMAC				(IRQ_OFFSET + 68)
#define IRQ_DWC_GMAC_LPI			(IRQ_OFFSET + 69)
#define IRQ_DWC_GMAC_PMT			(IRQ_OFFSET + 70)
#define IRQ_VIP2_SYNC				(IRQ_OFFSET + 71)
#define IRQ_VPU_IDLE				(IRQ_OFFSET + 72)
#define IRQ_VPU_INTR				(IRQ_OFFSET + 73)
#define IRQ_TIMER1_INT0				(IRQ_OFFSET + 74)
#define IRQ_TIMER1_INT1				(IRQ_OFFSET + 75)
#define IRQ_TIMER1_INT2				(IRQ_OFFSET + 76)
#define IRQ_TIMER1_INT3				(IRQ_OFFSET + 77)
#define IRQ_PPM_INT9				(IRQ_OFFSET + 78)
#define IRQ_PPM_INT10				(IRQ_OFFSET + 79)
#define IRQ_PPM_INT11				(IRQ_OFFSET + 80)
#define IRQ_PPM_INT12				(IRQ_OFFSET + 81)
#define IRQ_PPM_INT13				(IRQ_OFFSET + 82)
#define IRQ_PPM_INT14				(IRQ_OFFSET + 83)
#define IRQ_PPM_INT15				(IRQ_OFFSET + 84)
#define IRQ_DMAW0				(IRQ_OFFSET + 85)
#define IRQ_DMAW1				(IRQ_OFFSET + 86)
#define IRQ_DMAW2				(IRQ_OFFSET + 87)
#define IRQ_DMAW3				(IRQ_OFFSET + 88)
#define IRQ_DMAW4				(IRQ_OFFSET + 89)
#define IRQ_DMAW5				(IRQ_OFFSET + 90)
#define IRQ_DISP_HUE0				(IRQ_OFFSET + 91)
#define IRQ_DISP_HUE1				(IRQ_OFFSET + 92)
#define IRQ_DISP_GAMMA0				(IRQ_OFFSET + 93)
#define IRQ_DISP_GAMMA1				(IRQ_OFFSET + 94)
#define IRQ_DISP_CROP0				(IRQ_OFFSET + 95)
#define IRQ_DISP_CROP1				(IRQ_OFFSET + 96)
#define IRQ_DISP_DMAR0				(IRQ_OFFSET + 97)
#define IRQ_DISP_DMAR1				(IRQ_OFFSET + 98)
#define IRQ_DISP_DMAR2				(IRQ_OFFSET + 99)
#define IRQ_DISP_DMAR3				(IRQ_OFFSET + 100)
#define IRQ_DISP_DMAR4				(IRQ_OFFSET + 101)
#define IRQ_DISP_DMAR5				(IRQ_OFFSET + 102)
#define IRQ_DISP_DMAR6				(IRQ_OFFSET + 103)
#define IRQ_DISP_DMAR7				(IRQ_OFFSET + 104)
#define IRQ_DISP_DMAR8				(IRQ_OFFSET + 105)
#define IRQ_DISP_DMAR9				(IRQ_OFFSET + 106)
#define IRQ_DISP_SCALER0			(IRQ_OFFSET + 107)
#define IRQ_DISP_SCALER1			(IRQ_OFFSET + 108)
#define IRQ_DISP_SCALER2			(IRQ_OFFSET + 109)
#define IRQ_DISP_CSI_TO_NXS0			(IRQ_OFFSET + 110)
#define IRQ_DISP_CSI_TO_NXS1			(IRQ_OFFSET + 111)
#define IRQ_DISP_CSI_TO_NXS2			(IRQ_OFFSET + 112)
#define IRQ_DISP_CSI_TO_NXS3			(IRQ_OFFSET + 113)
#define IRQ_DISP_MULTI_TAP0			(IRQ_OFFSET + 114)
#define IRQ_DISP_MULTI_TAP1			(IRQ_OFFSET + 115)
#define IRQ_DISP_MULTI_TAP2			(IRQ_OFFSET + 116)
#define IRQ_DISP_MULTI_TAP3			(IRQ_OFFSET + 117)
#define IRQ_DISP_LVDS0				(IRQ_OFFSET + 118)
#define IRQ_DISP_SBUS				(IRQ_OFFSET + 119)
#define IRQ_DISP_PPMU				(IRQ_OFFSET + 120)
#define IRQ_DISP_SYNC_IRQ			(IRQ_OFFSET + 121)
#define IRQ_NXS_TO_MIPIDSI			(IRQ_OFFSET + 122)
#define IRQ_VIP3_SYNC				(IRQ_OFFSET + 123)
#define IRQ_CSC0				(IRQ_OFFSET + 128)
#define IRQ_CSC1				(IRQ_OFFSET + 129)
#define IRQ_CSC2				(IRQ_OFFSET + 130)
#define IRQ_CSC3				(IRQ_OFFSET + 131)
#define IRQ_MLCPRI				(IRQ_OFFSET + 132)
#define IRQ_SEC					(IRQ_OFFSET + 133)
#define IRQ_VIP0				(IRQ_OFFSET + 134)
#define IRQ_VIP1				(IRQ_OFFSET + 135)
#define IRQ_VIP2				(IRQ_OFFSET + 136)
#define IRQ_VIP3				(IRQ_OFFSET + 137)
#define IRQ_DMA0				(IRQ_OFFSET + 139)
#define IRQ_DMA1				(IRQ_OFFSET + 141)
#define IRQ_SDMA0				(IRQ_OFFSET + 143)
#define IRQ_SDMA1				(IRQ_OFFSET + 145)
#define IRQ_PKA					(IRQ_OFFSET + 146)
#define IRQ_ISP_CPUIF				(IRQ_OFFSET + 147)
#define IRQ_ISP_CORE0				(IRQ_OFFSET + 148)
#define IRQ_ISP_CORE1				(IRQ_OFFSET + 149)
#define IRQ_ISP_CORE2				(IRQ_OFFSET + 150)
#define IRQ_ISP_CORE3				(IRQ_OFFSET + 151)
#define IRQ_ISP_CORE4				(IRQ_OFFSET + 152)
#define IRQ_WAVE420_VPU_IDLE			(IRQ_OFFSET + 153)
#define IRQ_WAVE420_VPU				(IRQ_OFFSET + 154)
#define IRQ_GPU					(IRQ_OFFSET + 156)
#define IRQ_GPU_INT1				(IRQ_OFFSET + 157)
#define IRQ_I2C3				(IRQ_OFFSET + 158)
#define IRQ_I2C4				(IRQ_OFFSET + 159)
#define IRQ_PWM1_INT0				(IRQ_OFFSET + 160)
#define IRQ_PWM1_INT1				(IRQ_OFFSET + 161)
#define IRQ_PWM1_INT2				(IRQ_OFFSET + 162)
#define IRQ_PWM1_INT3				(IRQ_OFFSET + 163)
#define IRQ_PWM2_INT0				(IRQ_OFFSET + 164)
#define IRQ_PWM2_INT1				(IRQ_OFFSET + 165)
#define IRQ_PWM2_INT2				(IRQ_OFFSET + 166)
#define IRQ_PWM2_INT3				(IRQ_OFFSET + 167)
#define IRQ_PWM3_INT0				(IRQ_OFFSET + 168)
#define IRQ_PWM3_INT1				(IRQ_OFFSET + 169)
#define IRQ_PWM3_INT2				(IRQ_OFFSE9 + 170)
#define IRQ_PWM3_INT3				(IRQ_OFFSET + 171)
#define IRQ_GPIOA				(IRQ_OFFSET + 172)
#define IRQ_GPIOB				(IRQ_OFFSET + 173)
#define IRQ_GPIOC				(IRQ_OFFSET + 174)
#define IRQ_GPIOD				(IRQ_OFFSET + 175)
#define IRQ_GPIOE				(IRQ_OFFSET + 176)
#define IRQ_GPIOF				(IRQ_OFFSET + 177)
#define IRQ_GPIOG				(IRQ_OFFSET + 178)
#define IRQ_ARM_EXTERR				(IRQ_OFFSET + 179)
#define IRQ_ARM_COMM0				(IRQ_OFFSET + 180)
#define IRQ_ARM_COMM1				(IRQ_OFFSET + 181)
#define IRQ_ARM_COMM2				(IRQ_OFFSET + 182)
#define IRQ_ARM_COMM3				(IRQ_OFFSET + 183)
#define IRQ_ARM_CTI0				(IRQ_OFFSET + 184)
#define IRQ_ARM_CTI1				(IRQ_OFFSET + 185)
#define IRQ_ARM_CTI2				(IRQ_OFFSET + 186)
#define IRQ_ARM_CTI3				(IRQ_OFFSET + 187)
#define IRQ_ARM_PMU0				(IRQ_OFFSET + 188)
#define IRQ_ARM_PMU1				(IRQ_OFFSET + 189)
#define IRQ_ARM_PMU2				(IRQ_OFFSET + 190)
#define IRQ_ARM_PMU3				(IRQ_OFFSET + 191)
#define IRQ_MCU_CORE				(IRQ_OFFSET + 200)
#define IRQ_NSX_FIFO11				(IRQ_OFFSET + 201)
#define IRQ_NSX_FIFO10				(IRQ_OFFSET + 202)
#define IRQ_NSX_FIFO9				(IRQ_OFFSET + 203)
#define IRQ_NSX_FIFO8				(IRQ_OFFSET + 204)
#define IRQ_AXIM_IRQ				(IRQ_OFFSET + 205)
#define IRQ_TPGEN0				(IRQ_OFFSET + 206)
#define IRQ_MLC_LAYER0				(IRQ_OFFSET + 207)
#define IRQ_MLC_LAYER1				(IRQ_OFFSET + 208)
#define IRQ_MLC_LAYER2				(IRQ_OFFSET + 209)
#define IRQ_MLC_LAYER3				(IRQ_OFFSET + 210)
#define IRQ_MLC_LAYER4				(IRQ_OFFSET + 211)
#define IRQ_MLC_LAYER5				(IRQ_OFFSET + 212)
#define IRQ_MLC_LAYER6				(IRQ_OFFSET + 213)
#define IRQ_MLC_LAYER7				(IRQ_OFFSET + 214)
#define IRQ_GPIOH				(IRQ_OFFSET + 215)
#define IRQ_DMAW6				(IRQ_OFFSET + 216)
#define IRQ_DMAW7				(IRQ_OFFSET + 217)
#define IRQ_DMAW8				(IRQ_OFFSET + 218)
#define IRQ_DMAW9				(IRQ_OFFSET + 219)
#define IRQ_DMAW10				(IRQ_OFFSET + 220)
#define IRQ_DMAW11				(IRQ_OFFSET + 221)
#define IRQ_MCD					(IRQ_OFFSET + 222)
#define IRQ_UART6				(IRQ_OFFSET + 223)
#define IRQ_UART7				(IRQ_OFFSET + 224)
#define IRQ_UART8				(IRQ_OFFSET + 225)
#define IRQ_PWM0_INT4				(IRQ_OFFSET + 226)
#define IRQ_PWM1_INT4				(IRQ_OFFSET + 227)
#define IRQ_PWM2_INT4				(IRQ_OFFSET + 228)
#define IRQ_PWM3_INT4				(IRQ_OFFSET + 229)
#define IRQ_TIMER0_INT4				(IRQ_OFFSET + 230)
#define IRQ_TIMER1_INT4				(IRQ_OFFSET + 231)
#define IRQ_NSX_FIFO7				(IRQ_OFFSET + 232)
#define IRQ_NSX_FIFO6				(IRQ_OFFSET + 233)
#define IRQ_NSX_FIFO5				(IRQ_OFFSET + 234)
#define IRQ_NSX_FIFO4				(IRQ_OFFSET + 235)
#define IRQ_NSX_FIFO3				(IRQ_OFFSET + 236)
#define IRQ_NSX_FIFO2				(IRQ_OFFSET + 237)
#define IRQ_NSX_FIFO1				(IRQ_OFFSET + 238)
#define IRQ_NSX_FIFO0				(IRQ_OFFSET + 239)
#define IRQ_MPEGTSI_TSI0			(IRQ_OFFSET + 240)
#define IRQ_MPEGTSI_TSI1			(IRQ_OFFSET + 241)
#define IRQ_PDM1				(IRQ_OFFSET + 242)
#define IRQ_PDM2				(IRQ_OFFSET + 243)
#define IRQ_PDM3				(IRQ_OFFSET + 244)
#define IRQ_CSI_TO_AXI0				(IRQ_OFFSET + 245)
#define IRQ_MDMA				(IRQ_OFFSET + 247)
#define IRQ_USB3_INT				(IRQ_OFFSET + 248)
#define IRQ_USB3_OTG				(IRQ_OFFSET + 249)
#define IRQ_USB3_ADP				(IRQ_OFFSET + 250)
#define IRQ_USB3_BC				(IRQ_OFFSET + 251)
#define IRQ_AUDIO_IO_CTRL			(IRQ_OFFSET + 252)
#define IRQ_MIPICSIS				(IRQ_OFFSET + 253)
#define IRQ_MIPIDSIM				(IRQ_OFFSET + 254)

#endif
