#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

obj-y += s5pxx18_drm_dp.o s5pxx18_soc_dp.o	\
		s5pxx18_soc_mlc.o s5pxx18_soc_dpc.o s5pxx18_soc_disptop.o
