#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

obj-y += nx_soc_mlc.o nx_soc_dpc.o  nx_soc_disptop.o nx_display.o

obj-$(CONFIG_NX_DISPLAY_LCD)   += nx_display_lcd.o

